# Script 1: Limpieza Datos TAGS

## Diccionario?

## Parte 0. Mount

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

## Parte 1. Datos Crudos - Unión de los Datasets

In [ ]:
# Se importan los datasets de la carpeta /DatosTags/Datasets/Crudo/csv
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% #
### 1. Consolidado 2024
c_2024 = pd.read_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edenred_Consolidado_2024.csv')
### 2. Consolidado 2023
c_2023 = pd.read_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edenred_Consolidado_Diciembre_2023.csv')
### 3. Consolidado 2022
c_2022 = pd.read_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edenred_Consolidado_2022.csv')
c_transaccion_2022 = pd.read_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edenred_Consolidado_2022_Sheet1.csv')#hoja 2
### 4. Consolidado 2021
c_2021 = pd.read_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edenred_Consolidado_2021.csv')
### 5. Consolidado 22 23 24 (creo que esta vacio)
Consumo = pd.read_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Consumo_en_Tag_22_23_24.csv')

In [ ]:
import pandas as pd

# Cargar el archivo CSV
Consumo = pd.read_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Consumo_en_Tag_22_23_24.csv')

# Contar celdas ocupadas (no nulas)
celdas_ocupadas = Consumo.notna().sum().sum()

print(f"Total de celdas ocupadas: {celdas_ocupadas}")

Total de celdas ocupadas: 0

In [ ]:
# Union de datasets marcados como "consolidado"

In [ ]:
import pandas as pd

# Cargar los archivos CSV
c_2024 = pd.read_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edenred_Consolidado_2024.csv')
c_2023 = pd.read_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edenred_Consolidado_Diciembre_2023.csv')
c_2022 = pd.read_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edenred_Consolidado_2022.csv')
c_2021 = pd.read_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edenred_Consolidado_2021.csv')

# Agregar columna de año a cada DataFrame
c_2024['Año'] = 2024
c_2023['Año'] = 2023
c_2022['Año'] = 2022
c_2021['Año'] = 2021

# Unir los DataFrames
consolidado = pd.concat([c_2024, c_2023, c_2022, c_2021], ignore_index=True)

# Identificar columnas únicas
columnas_unicas = consolidado.columns.tolist()

print(f"Número total de columnas en el dataset unificado: {len(columnas_unicas)}")
print("Listado de columnas en el dataset final:")
print(columnas_unicas)

# Guardar el resultado en un nuevo CSV
consolidado.to_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edenred_Consolidado_Final.csv', index=False)

Número total de columnas en el dataset unificado: 70
Listado de columnas en el dataset final:
['Month', 'Id Grupo Región', 'Grupo de Región ', 'Cliente', 'Factura', 'PO', 'GR', 'Id Región', 'Serie', 'No Economico', 'Division', 'BL', 'BL2', 'SUB BL', 'CC', 'Identificador Vehículo', 'Vehículo', 'VIN NUMBER', 'Placa', 'Num Tarjeta', 'Num Serie', 'Fecha Transacción', 'Hora Transacción', 'No Comprobante', 'Id Mercancía', 'Mercancía', 'Km Ant Transacción', 'Km Transacción', 'Recorrido', ' Importe Neto', ' IVA', 'IVA %', 'IEPS', 'Importe Transacción', 'Importe Transacción.1', 'Comision', 'Subtotal', 'Cantidad Mercancía', 'KG C02', 'TON C02', 'Arboles', 'Precio Unitario', 'Rendimiento', 'Rendimiento Real', 'Id Conductor', 'Conductor', 'No Estación Pemex', 'Razón Social Afiliado', 'RFC', 'Número de Control', 'Folio', 'Observación', 'Respuesta', 'Unnamed: 53', 'Año', 'Importe Neto', 'IVA', 'Estado', 'BL 2 ', 'VIN Number', 'Locacion', 'No. Economico', 'Sub BL', 'Old BL', 'AU', 'AC', 'CONCATENATE', 'VALID', 'Serie.1', 'Estado de Carga']

In [ ]:
consolidado.iloc[0:,]

,Month,Id Grupo Región,Grupo de Región,Cliente,Factura,PO,GR,Id Región,Serie,No Economico,...,Locacion,No. Economico,Sub BL,Old BL,AU,AC,CONCATENATE,VALID,Serie.1,Estado de Carga
0,ene-24,2,MCA2,02125-031,TCGE000003146706,PENDIENTE,PENDIENTE,1000,1FTMF1CB6NKE14608,993-VH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,dic-24,ene-00,MCA2,02125-031,TCGE000003611447,4793681915,NaN,sep-02,3N6CD33BXPK837919,123-REY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ene-24,2,MCA2,02125-031,TCGE000003146706,PENDIENTE,PENDIENTE,1000,1FTFW1CD5NFB41759,927-VH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ene-24,2,MCA2,02125-031,TCGE000003142973,PENDIENTE,PENDIENTE,1003,1FTMF1CB8PKD69206,120-VH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ene-24,2,MCA2,02125-031,TCGE000003144894,PENDIENTE,PENDIENTE,1001,1FMCU0BZ0MUA90533,875-VH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48764,Dec,12,NaN,MCA2,02125-031,NaN,NaN,TCGE000002205827,1FTEX1CMXDKD62983,NaN,...,2,1700-VH,CFLC,CFLC,MX100045,MX100045,MX100045,VALID,1FTEX1CMXDKD62983,Tabasco
48765,Dec,12,NaN,Marine,02125-021,NaN,NaN,Pendiente,Equipment,NaN,...,DOWELL,Equipment,WIS,WIS,MX100018,MX100018,MX100018,VALID,Equipment,Tabasco
48766,Dec,12,NaN,Marine,02125-021,NaN,NaN,Pendiente,Equipment,NaN,...,DOWELL,Equipment,WIS,WIS,MX100018,MX100018,MX100018,VALID,Equipment,Tabasco
48767,Dec,12,NaN,Marine,02125-021,NaN,NaN,Pendiente,km14.5,NaN,...,DOWELL,km14.5,SBS,SBS,MX100057,MX100057,MX100057,VALID,km14.5,Tabasco
48768,Dec,12,NaN,Marine,02125-021,NaN,NaN,Pendiente,km14.5,NaN,...,DOWELL,km14.5,SBS,SBS,MX100057,MX100057,MX100057,VALID,km14.5,Tabasco

Notas acerca de las columnas
- BL1 y Bl2 Aparentemente son iguales
- Vehiculo y VIN NUMBER son lo mismo #La diferencia es que Vehiculo es "Unidad + VIN NUMBER"
- Importe Transacción se repite (Eliminar Importe Transacción.1)
- Unamed: 53 (No tiene datos)
- en la columna Month, hay algunos meses marcados como ene-24, año y mes juntos.


Unificar Base de Sub Bl (con "SUB BL") y BL2 (on "BL 2") del 2022

Unir Estado de Carga, con "Estado"

Ver que significa Serie.1

Separar mes y año de la columna month, unificar formato.

Eliminar cualquier columna sin datos

In [ ]:
import pandas as pd

# Supongamos que "consolidado" es tu DataFrame principal y "c_2022" es otro DataFrame para el 2022

# Unificar BL y BL2 (asumiendo que son iguales)
consolidado['BL'] = consolidado['BL'].combine_first(consolidado['BL2'])
consolidado.drop(columns=['BL2'], inplace=True)

# Unificar Vehículo y VIN NUMBER (donde Vehículo ya contiene "Unidad + VIN NUMBER")
consolidado['Vehículo'] = consolidado['Vehículo'].combine_first(consolidado['VIN NUMBER'])
consolidado.drop(columns=['VIN NUMBER'], inplace=True)

# Eliminar columna duplicada de Importe Transacción
consolidado.drop(columns=['Importe Transacción.1'], inplace=True)

# Eliminar Unnamed: 53 si existe
if 'Unnamed: 53' in consolidado.columns:
    consolidado.drop(columns=['Unnamed: 53'], inplace=True)

# Unificar Base de Sub BL y BL2 del 2022 en el DataFrame c_2022, si existen ambas columnas
if 'SUB BL' in c_2022.columns and 'BL 2' in c_2022.columns:
    c_2022['SUB BL'] = c_2022['SUB BL'].combine_first(c_2022['BL 2'])
    c_2022.drop(columns=['BL 2'], inplace=True)

# Unir Estado de Carga con Estado
consolidado['Estado'] = consolidado['Estado'].combine_first(consolidado['Estado de Carga'])
consolidado.drop(columns=['Estado de Carga'], inplace=True)

# Revisar qué significa Serie.1 (se imprime para análisis manual)
if 'Serie.1' in consolidado.columns:
    print("Valores únicos en Serie.1:")
    print(consolidado['Serie.1'].unique())

# ====================================================
# Procesamiento de la columna Month y la columna Año
# ====================================================

# Procesar la columna Month para separar mes y año cuando aparezcan juntos
# Se identifica si en Month aparece un guion ("-") que indique que contiene ambos datos.
mask = consolidado["Month"].astype(str).str.contains("-")
if mask.any():
    # Se separa en dos partes: la izquierda es el mes y la derecha es el año
    splits = consolidado.loc[mask, "Month"].str.split("-", expand=True)
    # Actualizar la columna Month con el valor del mes
    consolidado.loc[mask, "Month"] = splits[0]
    # Actualizar la columna Año únicamente donde se encuentre vacío
    consolidado.loc[mask & consolidado["Año"].isna(), "Año"] = splits[1]

# Función para formatear el año a 4 dígitos si aparece en formato de 2 dígitos
def format_year(x):
    try:
        x_str = str(x).strip()
        if len(x_str) == 2 and x_str.isdigit():
            return "20" + x_str
    except Exception as e:
        return x
    return x

# Aplicar el formateo a la columna Año
consolidado["Año"] = consolidado["Año"].apply(format_year)

# Unificar el formato de la columna Month: convertir abreviaturas a nombres completos en español
month_map = {
    "ene": "Enero", "jan": "Enero",
    "feb": "Febrero",
    "mar": "Marzo",
    "abr": "Abril", "apr": "Abril",
    "may": "Mayo",
    "jun": "Junio",
    "jul": "Julio",
    "ago": "Agosto", "aug": "Agosto",
    "sep": "Septiembre",
    "oct": "Octubre",
    "nov": "Noviembre",
    "dic": "Diciembre", "dec": "Diciembre"
}

# Se aplica la conversión: se pasa a minúsculas y se mapea utilizando el diccionario. Si no coincide, se mantiene el valor original.
consolidado["Month"] = consolidado["Month"].str.lower().map(month_map).fillna(consolidado["Month"])

# ====================================================
# Eliminamos cualquier columna sin datos
consolidado.dropna(axis=1, how='all', inplace=True)

# Identificar columnas únicas
columnas_unicas = consolidado.columns.tolist()

print(f"Número total de columnas en el dataset unificado: {len(columnas_unicas)}")
print("Listado de columnas en el dataset final:")
print(columnas_unicas)

# Guardar el resultado en un nuevo CSV
consolidado.to_csv('/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edendred_Consolidado_Final.csv', index=False)

Valores únicos en Serie.1:
[nan '1FTEX1CM3EKF41710' '1FTMF1EB5JKE74032' '1FDWF3G67KEE38116'
 '1FTMF1EB9JFA48661' '1FTMF1EF2EKD19348' 'WF0CP6A76H1C07201'
 '1FBAX2CM2HKA24475' '1FTMF1CM2DKF89244' 'WF0CP6A71J1C54318'
 'WF0CP6A75J1C82381' '1FTMF1C8XGKD98758' '1FBAX2CM4HKA24459'
 '1FTMF1CM5CKD91403' '1FDEF3G69CED10845' '1FTEX1CM3DKG15044'
 '1FBAX2CM3KKA33676' 'WF0CP6A7XH1C08576' '1FBAX2CMXHKA24403'
 '1FTMF1E52JKC98518' '1XP6XEEX1TD609280' 'WF06S5JPXKTC35052'
 '3WKDD40X3DF848408' 'WF0CP6A71K1D32713' '1FTMF1E57JKC06402'
 '1NKDL4EX5AR269614' 'WF0CP6A73J1C57575' '1FTMF1E55JKE99779'
 'WF0CP6A78K1D19358' 'WF0CP6A77K1D03037' '1FTMF1EF8HFA04972'
 '1FTMF1C81GKD98776' '3FDKF36L05MA04172' '1FTMF1CB7JFD47696'
 '1FBAX2CM6HKA24401' '1FTMF1CM5EKF66610' '1FTEW1CB6JKF47318'
 'WF0CP6A72K1C98779' '3HAMPAFL0BL409685' '1FTMF1EB7JFA48660'
 'WF0CP6A73J1C84999' '1FMCU0F70DUC50399' '1FTEX1CM8DKD62979'
 '1FTEX1CM9EKE86700' '1FTMF1E52JKD63030' '1FTMF1E56JKE40675'
 '1FBAX2CM0HKA42733' '1FTMF1CM5CKD91398' '1FTEX1CMXDKD62983'
 '1FTMF1E5XJKC11464' '1FTMF1EB3JKE74126' '1FBAX2CM4KKA22427'
 '1FDEF3G60BEA29323' '1FTMF1CB1JFA48608' '1NKDX4EX1ER368070'
 '1XKDP4TX9CR310908' '1FTMF1C82GKF24482' '1FTMF1CBXJFD47725'
 '1FBAX2CM4HKA24445' '3WKDDB0X99F820818' '1FTMF1CB1JFD47726'
 '1FTMF1CB5JFD47714' '1NKDX4EX5ER368069' '1FBAX2CM5HKA24471'
 '1FBAX2CMXHKA24451' '1FTMF1EF3HFA05141' '3WKADB0X13F613608'
 'WF06S5JP9JTA49274' '1FTEX1CM1DKD62984' '1FTMF1E55JKC98481'
 '1FTMF1E59JKE42257' '1FBAX2CM7KKA33681' '1FTMF1E52JKC11541'
 'WF06S5JP0JTA39619' '1FTEX1CM5EKF13102' '1FTEX1CM0EKE60874'
 'WF0CP6A77H1C16344' '1FTMF1CB4JKC06401' 'WF0CP6A71J1C68431'
 '1FTMF1E55JKE99569' '1FTMF1C83GKD98701' '1FTMF1EBXJFA11991'
 '1FTRF04V79KA54683' '1FTMF1C81GKD98745' '1FTMF1EF7EKD19362'
 '1FBAX2CM5HKA24468' 'WF0CP6A74K1D33340' '1FTEX1CM0EKE42004'
 '1FTMF1C81GKD98728' '1FBAX2CM1KKA25124' '1FTMF1CM1DKF62939'
 '1FDWF3G60JEB86949' 'WF0CP6A74H1C16334' '1FTMF1EB5JFA48673'
 '1FTEX1CM8DKD62996' 'WF06S5JPXFTA00799' 'WF0CP6A77H1C16361'
 '1FTMF1CBXJKC01140' '1FTMF1CM5EKF66834' '1FBAX2CM5KKA33680'
 '1FTMF1CM8DKF62856' '1FTMF1E58JKE26485' '1FTMF1EB1JFA48668'
 '3FELF46R18MA35512' '1FTMF1E56JKC01174' '1FTRF04V59KA96110'
 '3WKDDB0X38F810297' '3HAMMAAR4BL354923' '1FTMF1CB5JFA34792'
 'VF634DPA79D005766' '1XKDP4TX4DR362531' '1FTMF1EF0HFA04948'
 '5KBRL5861EB806671' '1FTEX1CM7EKD88362' 'WF0CP6A71K1D42514'
 '3WKDDB0X78F810299' '1FTMF1CM4DKF89231' '1FTMF1CM7CKD91421'
 '3WKDDB0X09F820819' 'WF0CP6A76H1C08610' 'WF06S5JP4JTA40188'
 '1FTMF1E57JKC11549' '1FTMF1C87GKD98734' '1FTMF1EM5CKD28217'
 '1FTMF1E50JKF47415' '1FTMF1EB9JFA48675' 'WF06S5JP4JTA52082'
 '1FTMF1CM7EKF66835' 'WF0CP6A71K1C98711' '1HTWBAAN84J030564'
 '1FTMF1E53JKF47392' '3WKDD40X8EF856974' '3WKDD40XXEF857110'
 'VF634DPA69D006455' 'WF0CP6A70J1C57842' '3WKDD40XXEF857107'
 '1NKDL4EX7DR347542' '3WKDD40XXCF840546' '1FTMF1C89GKD98704'
 '1FTMF1C80GFC89220' '1FBAX2CM3HKA24470' '1FTMF1CB9JKD27604'
 'WF0CP6A73J1C54322' '3HSCNAST69N071484' '3WKDD40X0DF848401'
 '1FTMF1E51JKE99777' '3WKDD40X8DF848405' 'WF0CP6A70K1D43993'
 'WF06S5JP5KTA89627' '1FTEX1CM2EKD88415' '1GDP7F1387F412319'
 '1FMCU0J95LUA03614' '1FTEX1CM6EKF85118' '1FTMF1E55JKC98514'
 'VF634DPA68D004137' '1FDAF4GT4HEB43361' '1FTMF1EB3JKE74109'
 'WF0CP6A77H1C07238' 'WF0CP6A75K1D03523' '1FTMF1C8XGKF24469'
 '3HAMMAAR19L121527' 'WF0CP6A79H1C08598' '1FTMF1C89GFC89233'
 '3WKDD40X9DF848400' '1HTWAAAR29J066490' '1FTMF1EB3JFA48669'
 'WF0CP6A71K1D42593' '1FTMF1CBXJFA48607' 'WF0CP6A73J1C54353'
 '1FTEX1CM7DKD63010' '3WKDDB0X19F820814' 'WF0CP6A77K1D16970'
 '3WKDD40X6DF848404' '1NKDXUEX19R252986' '1HTWNADT94J016996'
 '3HAMMAARXBL354862' '1NKDL4EX3AR269613' '3WKDD40X6DF848807'
 '1FTMF1CB0JKD76593' 'WF06S5JP3JTA40229' '1NPALT0X57D732517'
 'Montacargas km14.5 y periferia' 'Facilities Poza Rica' 'CT Equipment'
 '321-REY-WL-Transit-JP4JTA52082' '1203-REY HSE F150 2018'
 '458-REY KENWORTH F607588' '310-REY-WL-Transit-JP0JTA39619'
 '601-REY F-150 4X4 E74093 SEC ' '312-REY-WL-Transit-JP4JTA40188'
 '103-REY FORD F-350 HEB43880' '316-REY F-350 XL E38116'
 '508-REY TPS-TRANSIT-24470' 'Prestada Unidad 645'
 '511-REY F-450 XL A15283' '1207-REY OFS HSE SEC' '1205-REY HSE F150 2018'
 'Provisional REY WSV-WPS 105' '602-REY F150-1FTMF1EB9JFA48675'
 'Provisional REY WSV-TF 110' 'Provisional REY WSV-TF 111'
 '814-REY F-150 4X2 D47723 HSE' '600-REY ESCAPE 2019 D32713'
 '959-REY ECONOLINE.2012' '919-REY F350 ALS'
 '852-REY TRANSIT WSV KTA89627' 'MN-1 N2 Unit'
 'Provisional REY WSV-WPS 108' 'Provisional REY WSV-WPS 104'
 '850-REY WS-WIT-TRANSIT-24445' '507-REY TPS-TRANSIT-24475'
 'Provisional REY WSV-WIT 100' '116-VH TRANSIT GASOLINA A33680'
 '1700-VH CAM FORD F150 DKD62983' '952-VH IDS FORD F-150 HFA04948'
 'P-29-VH FORD Crew Cab' '966-VH IDS LOBO XLT KE99777'
 '1409-VH MI F-150 XL 4X2' 'Prestamo Viajes WTS' '962-VH IDS PEP'
 '175-VH RENAULT D004137' '964-VH IDS PEP LOBO XLT' '135-VH PLANA HIAB 3'
 '1335-VH F 150.2013 M2DKF89244' '695-VH FORD ESCAPE DUB34635'
 '514-VH FORD ESCAPE H1C08597' '518-VH FORD ESCAPE H1C08576'
 '1108-VH ESCAPE DPM D19358' '783-VH F 150.2013'
 '1719-VH CAMERON F150 4X2' '1406-VH FORD F-150 GKD98745'
 '1709-VH CAM FORD F150 DKD62979' '5510-VH FORD F-150 GKD98758'
 'P-11-VH CAM FORD F150 EKE60874' '706-VH FORD ESCAPE J1C54318'
 '888-VH FORD F-150 GKD98701' '635-VH ESCAPE.2013' '118-VH TRANSIT REW '
 'P-09 Prestamo POOL' '206-VH FORD F-150 2016 D98734'
 '761-VH F 150.2014 DKD27848' '117-VH TRANSIT GASOLINA A33681'
 '1405-VH MI DRILLING' '756-VH ESCAPE.2014' '539-VH WTS ESCAPE 2019'
 '1706-VH CAM FORD F150 EKD88362' '948-VH IDS LOBO XLT KF47415'
 '167-VH GRUA-5073 INTERNATIONAL' '635-VH FORD ESCAPE H1C16334'
 '947-VH IDS LOBO XLT KE42257' '1107-VH F 150.2014 EKF66610'
 '1705-VH CAM FORD F150 EKE86700' '231-VH WPS TRANSIT 350 MR '
 '1403-VH MI DRILLIN' '145-VH ESCAPE 2019 D03037'
 '532-VH WTS FORDESCAPE H1C08610' 'P-10-VH CAM FORD F150 EKE42004'
 '2214-VH WS F150 XL KD98704' '105-VH WL F150 2018'
 '1702-VH CAM FORD F150 DKD62984' '967-VH FORD F-150 HFA05141'
 '945-VH IDS LOBO XLT KE26485' '965-VH IDS LOBO XLT KE99779'
 '960-VH FORD LOBO JKC01174' '963-VH IDS PEP' '958-VH FORD LOBO JKC11541'
 'P-28 POOL ESCAPE 2019' '1408-VH MI F-150 XL D47714'
 '5506-VH FORD ESCAPE H1C08598' '687-VH FORD ESCAPE DUB04932'
 '943-VH IDS ESCAPE C99201' '503-VH FORD ESCAPE H1C16356'
 '267-VH FORD F-150 GKD98728' '954-VH FORD LOBO 2018 C11464'
 '1401-VH MI DRILLING' '3ESC-VH F 350.2005' '184-VH PLANA HIAB 1'
 '553-VH WTS KENWORTH' '506-VH FORD ESCAPE' '957-VH FORD LOBO JKC06402'
 '946-VH IDS LOBO XLT KF47392' '269-VH WS F150 4X2 2018 '
 '1711-VH CAM FORD F150 DKD62996' '757-VH ESCAPE 2013'
 '754-VH ALS LOBO 2018' '702-VH FUSION.2013' '189-VH F150 2014'
 '115-VH OSLC-GAC-5845' 'P-22 POOL ESCAPE 2019' '1410-VH ESCAPE MI D16970'
 'BATALLON 37' '505-VH FORD ESCAPE J1C54353' 'P-35-VH ESCAPE 2013 C50399'
 '510-VH FORD ESCAPE 2018' '638-VH FORD TRANSIT WSV A70583'
 '784-VH CPS F 150.2014' '2213-VH FORD TRANSIT HKA24401'
 '763-VH F150 2014' '177-VH OSLC-GAA-5849' '1404-VH MI DRILLIN'
 '5504-VH INTERNATIONAL WTS' '704-VH Odyssey.2014'
 '968-VH OFS RES LOBO 2018' '190-VH FORD F-150 EKF66848' '961-VH IDS PEP'
 '818-VH SIS ESCAPE' '955-VH FORD LOBO JKC11549' '1402-VH MI DRILLIN'
 '537-VH WTS FORDESCAPE H1C07201' '717-VH F-150 XL 4X2 D47675'
 '109-VH OSLC-GAC-E-5843' '337-VH FORD TRANSIT HKA24468'
 '1703-VH CAM FORD F150 EKD88415' '941-VH IDS HSE ESCAPE 2018'
 'PRESTAMO 504-VH WTS' '759-VH FORD F150 DKD27937'
 '716-VH OFS FORD F150 GKD98723' '889-VH FORD F150 2013 DKF62856'
 '127-VH KENWORTH 5101' '940-VH IDS HSE ESCAPE 2018'
 '1701-VH CAM FORD F150 DKG15044' '1716-VH CAM FORD F150 EKF13102'
 'P-05-VH LOBO 2009' '201-VH WS ' '723-VH F-150 XL 4X4 E74109'
 '724-VH F-150 XL 4X4 E74126' 'P-12 POOL ESCAPE 2019'
 '129-VH OSLC-GAA-E-5856' 'PRESTADA A LA UNIDAD P-07-VH'
 '162-VH PLANA HIAB' '721-VH OFS-MTC FORD F150' '178-VH GRUA5103 KENWORTH'
 '177-VH PRESTADA' '71-CAR F150' '141-CAR F-150 2012'
 '722-CAR OFS FORD F-150 ' '23-CAR WTT' '1420-CAR F-150 2014'
 '1190-PR IPS FORD LOBO' '299-PR KW T800B AR269613'
 '767-PR ALS F150 2016 D98746' 'Provisional WSV-WIT 101'
 '1702-PR MI F150 B9JKD27604' '277-PR ULTRAC-7072'
 '765-PR ALS FOR F1504X4' '651-PR SEG FORD F150 JFA48669'
 '234-PR FORD F150 WL' '1605-VH F-150 SAXON' 'VIAJES WL'
 'Provisional WSV-CTS 112' '297-PR PLANA HIAB 2'
 '1547-PR WPS TRANSIT A33676' 'Provisional WSV-WPS 110'
 '764-PR ALS FORD F150 4X2 ' 'VIAJES WS' '144-PR F-150 2012 D91403'
 '718-PR HSE ESCAPE 2019 C98779' '726-PR F-150 SECURITY' '279-PR SWPT-408'
 '1548-PR FRA TRANSIT A24459 ' '232-VER PLANA INTERNATIONAL'
 'Provisional WSV-WIT 102' 'VIAJES' 'Generador OFS-Eq. Facility PR'
 'POLVORIN MXE' 'Provisional WSV-WIT 103' '2062-PR FORD TRANSIT JTA49274'
 'Provisional WSV-WIT 100' 'Provisional WSV-WPS' 'Provisional WSV-WPS 109'
 'Provisional WSV-CTS 111' '1FTMF1C82GKD98723' '3WKDD40X7DF847620'
 '3WKADB0X89F824975' '3WKDD40X6DF847625' '1FTMF1CB6JFD47723'
 '3HTWGADT97N472475' '3WKDDB0X59F821738' '3WKDDB0X57F805357'
 '1FTMF1EB0JFE52447' '1FTEX1CM8DKD62982' '3WKDD40X4DF847624'
 '1FTEX1CM1DKD63004' 'VF634DPA69D005757' '1FTEX1CM2EKF66548'
 'WF0CP6A73H1C16356' '3WKDDB0X18F810301' '1FTMF1EB8JFA48666'
 '1NKDLU0X89R252857' 'WF0CP6A77H1C16358' '3WKDDB0X08F813402'
 '3WKDD40XXDF848406' '5KBRL3883AB801892' '1FDAF4GTXKDA15283'
 '1FTMF1CM6DKD27937' '1NKDX4EX4DR360978' '3WKADB0X83F613542'
 '3WKDD40X1DF848407' '3WKDD40X3EF857112' '3WKDD40X5EF854633'
 '1FTMF1CBXJFD47675' '1FTMF1CM5EKF66848' '1FTMF1EBXJFA48670'
 '3BKHLN9X3EF301657' '1FVDBXAK52HJ31499' '3BKHLN0X2EF399612'
 '3WKDD40X8EF857106' '3WKDD40X1EF857108' '3WKDD40X9EF857101'
 '3WKDD40X4EF857104' '3WKDD40X6EF857105' 'VF634DPA27D000973'
 '1NKDLU0XX9J255581' '3WKDDB0X08F810290' '1FTMF1EB3JKE74093'
 '1XKDDB0X88R816321' '3WKDD40X1EF857111' '1FTMF1EB0JFA48662'
 '3WKDD40X6DF848399' '3WKDD40X9DF847618' '3WKDD40X0DF848804'
 '3BKHLN9XXEF301476' 'WF0CP6A74H1C46708' '3WKDD40X2EF857098'
 'WF0CP6A75K1C99201' '1XKDDB0XX8R816319' 'Escape' 'VF634DPA69D005399'
 '3HAMSADR84L689123' '1XKDDB0X88R816318' '3WKADB0X33F613531'
 '3WKDD40X2DF847623' '3WKDD40X5DF846904' '1HTWNAZT37J402844'
 '1GCRC9E06DZ169436' '1FTEW1CB7MKD18909' '1FDAF4GT0HDA00428'
 '3WKDD40X4EF857006' 'WF0CP6A77H1C08597' '1FDWF3G66HEB43355'
 '1XKDDB0X38R816324' '1FTEW1CB4MKD24781' '1FDWF3G63HEB43880'
 '1FDGF5GT5EEA24570' 'WF0CP6A73J1C53655' 'WF0CP6A76J1C82423'
 '1HTWAAAR29J101495' '1FTMF1E51JKC01258' '3WKDD40X0EF857424'
 '1XPSD79X7CD139981' 'Equipment' 'Poza' 'km14.5' '959-REY' '1209-REY'
 'KTA89627' '312-REY' 'JFA48672' '940REY' 'JKC01140' 'EUE17141' 'F412319'
 '1XKDDB0X28R816329' '3BKMLD9X32F301498' '3WKADB0X02F608642'
 '3WKDDB0X29F821731' '3HAWBAAR3FL687828' '1GDP7F1347F412558'
 '3WKADB0X09F823173' '1XKDDB0X58R816325' '3BKHLN0X7BF375804'
 '3WKDD40X2DF848402' '1FDWF3G64HEB55276' '1FTMF1EB3JFA48672'
 '1FTMF1CM9EKD35449' '1FBSS3BL2CDA74954' '1XKDP4TX0ER387699'
 '1NKDX4EX0FR430513' '3WKADB0X14F613741' '1NKDL4EX1AR269612'
 '3WKDD40X2EF857103' '1FTMF1CB0MKD78221' '3WKDD40X4DF848806'
 '3WKDD40X2DF848805' '1XKDDB0X68R816320' '1FTFW1CD0MFA97460'
 '3WKDDB0X17F806148' '1FDAF4GT9KEE44991' '3BKHLN0X4EF399613'
 '3WKADB0X99F823172' '1FTFW1CD0MFA97547' '3WKDD40X0EF857102'
 '3WKDD40X4EF856972' '3WKDD40X0DF847619' '3WKDD40X4EF857099'
 '3WKDDB0X98F808845' '3BKHHM8XXEF395291' 'VF634DPA69D005743'
 '3FA6P0G77ER161161' '1FTFW1CD1MFA97466' '1FMCU0BZ7MUA00584'
 '1FTFW1CD6MFA97463' 'WF0CP6A73K1C99228' '1FTFW1CDXMFA97465'
 '1XPSDU9X0BD122453' '1FTFW1CD0MFA97457' '3WKDDB0X88F810294'
 '3WKADB0X42F607588' '3HAMSADR57L512680' '3WKADB0X83F613606'
 '3WKADB0X53F613529' '3WKDD40XxDF848809' '3WKDD40X4DF848403'
 '3WKDD40X7EF857100' '1FTEW1CB0MKE29592']

<ipython-input-25-f0e2ac161bf5>:47: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  consolidado.loc[mask & consolidado["Año"].isna(), "Año"] = splits[1]

Número total de columnas en el dataset unificado: 65
Listado de columnas en el dataset final:
['Month', 'Id Grupo Región', 'Grupo de Región ', 'Cliente', 'Factura', 'PO', 'GR', 'Id Región', 'Serie', 'No Economico', 'Division', 'BL', 'SUB BL', 'CC', 'Identificador Vehículo', 'Vehículo', 'Placa', 'Num Tarjeta', 'Num Serie', 'Fecha Transacción', 'Hora Transacción', 'No Comprobante', 'Id Mercancía', 'Mercancía', 'Km Ant Transacción', 'Km Transacción', 'Recorrido', ' Importe Neto', ' IVA', 'IVA %', 'IEPS', 'Importe Transacción', 'Comision', 'Subtotal', 'Cantidad Mercancía', 'KG C02', 'TON C02', 'Arboles', 'Precio Unitario', 'Rendimiento', 'Rendimiento Real', 'Id Conductor', 'Conductor', 'No Estación Pemex', 'Razón Social Afiliado', 'RFC', 'Número de Control', 'Folio', 'Observación', 'Respuesta', 'Año', 'Importe Neto', 'IVA', 'Estado', 'BL 2 ', 'VIN Number', 'Locacion', 'No. Economico', 'Sub BL', 'Old BL', 'AU', 'AC', 'CONCATENATE', 'VALID', 'Serie.1']

## Ultima limpieza
Eliminar columnas con 75% de datos vaciós o nulos

In [ ]:
import pandas as pd

# Cargar el DataFrame consolidado
ruta_archivo = "/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edendred_Consolidado_Final.csv"
df = pd.read_csv(ruta_archivo)

# Calcular el porcentaje de valores nulos por columna
umbral = 0.75  # 75% o más de valores nulos
columnas_a_eliminar = df.columns[df.isnull().mean() >= umbral]

# Eliminar las columnas con demasiados nulos
df_limpio = df.drop(columns=columnas_a_eliminar)

# Guardar el DataFrame limpio
ruta_guardado = "/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edendred_Consolidado_Limpio.csv"
df_limpio.to_csv(ruta_guardado, index=False)

# Mostrar columnas eliminadas
print(f"Columnas eliminadas ({len(columnas_a_eliminar)}): {list(columnas_a_eliminar)}")
print(f"Archivo guardado en: {ruta_guardado}")

<ipython-input-26-8ba31a072dc0>:5: DtypeWarning: Columns (2,5,6,9,12,13,21,22,27,28,30,34,39,41,43,46,47,51,52,53,54,55,56,57,58,59,60,61,62,63,64) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_archivo)

Columnas eliminadas (2): [' Importe Neto', ' IVA']
Archivo guardado en: /content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edendred_Consolidado_Limpio.csv

## Que celdas nos importan?
Preguntas y posibles respuestas

1. Identificar patrones y tendencias en el consumo de combustible

    Variables clave:

        Fecha Transacción, Hora Transacción: Analizar tendencias temporales (diarias, mensuales, estacionales).

        Id Grupo Región, Grupo de Región, Id Región: Para analizar variaciones geográficas.

        Vehículo, Placa, Num Serie, Identificador Vehículo, No Economico: Para identificar patrones específicos por vehículo.

        Mercancía, Cantidad Mercancía: Relación entre el tipo de carga y consumo.

        Rendimiento, Rendimiento Real: Evaluación de eficiencia de combustible.

        Kg CO2, TON CO2, Arboles: Relación entre consumo y huella ambiental.

2. Predecir el consumo de combustible futuro

    Variables clave:

        Fecha Transacción, Hora Transacción, Month, Año: Permiten modelar series de tiempo.

        Recorrido, Km Transacción, Km Ant Transacción: Para modelar consumo en función del recorrido.

        Importe Neto, IVA, Subtotal, Precio Unitario, Importe Transaccion: Impacto de precios en el consumo.

        Comision, IEPS, IVA %: Impacto de impuestos y comisiones.

        No Estación Pemex, Razón Social Afiliado: Identificación de estaciones con mayor consumo.

3. Optimizar la eficiencia del costo del combustible y reducir desviaciones

    Variables clave:

        Importe Transacción, Subtotal, Precio Unitario; Para analizar variaciones en costos.

        Rendimiento, Rendimiento Real: Para identificar vehículos menos eficientes.

        Estado: Impacto de ubicación en el rendimiento.

        Tipo de Mercancía, Cantidad Mercancía: Relación entre carga y consumo.

        No Estación Pemex: Estaciones con precios más altos o menor eficiencia.

4. Identificar patrones de consumo por tipo de vehículo y estación de servicio

    Variables clave:

        Vehículo, Placa, Num Serie, VIN Number: Para identificar patrones por vehículo.

        No Estación Pemex, Razón Social Afiliado: Para segmentar por estaciones de servicio.

        Recorrido, Cantidad Mercancía: Relación entre distancia y consumo.

        Precio Unitario, Importe Transacción, IVA, IEPS: Para analizar costos por estación.

5. Exploracion y otos:

    Variables clave:

        Vehículo, Placa, Num Serie, VIN Number, Id Grupo Región, Grupo de Región, Id Región, Estado: Graficar el recorrido de los vehiculos.

        No Estación Pemex, Razón Social Afiliado: Para segmentar por estaciones de servicio.

        Recorrido, Cantidad Mercancía: Relación entre distancia y consumo.

        Precio Unitario, Importe Transacción, IVA, IEPS: Para analizar costos por estación.

Columnas menos relevantes:

    Serie.1, CONCATENATE, VALID, Old BL, AU, AC: Pueden no aportar información clave al análisis. (Contienen información más administrativa, o de identificación ya otorgada por otras columnas

## Parte 2 - Consolidación de dataset para exploracion de datos:

Se busca eliminar las columnas menos relevantes para la exploracion de datos (Serie.1, CONCATENATE, VALID, Old BL, AU, AC)

In [ ]:
import pandas as pd
import numpy as np

# Función para limpiar y convertir columnas monetarias que puedan tener símbolos de dólar y comas
def limpiar_a_float(x):
    try:
        # Convertir a string, quitar símbolos y comas y luego a float
        if isinstance(x, str):
            x = x.replace('$','').replace(',','').strip()
        return float(x)
    except Exception:
        return np.nan

# Función para limpiar el campo de Id Conductor: quitar $ y comas, manteniendo tipo objeto (cadena)
def limpiar_id_conductor(x):
    try:
        if isinstance(x, str):
            return x.replace('$','').replace(',','').strip()
    except Exception:
        return x
    return x

# Cargar el DataFrame original
ruta_original = '/content/gdrive/MyDrive/Datos_TAGS/Datasets/Crudo/csv/Edendred_Consolidado_Limpio.csv'
final = pd.read_csv(ruta_original)

# --------------------------
# 1. Eliminar columnas innecesarias (si existen)
# --------------------------
columnas_a_eliminar = ['Serie.1', 'CONCATENATE', 'VALID', 'Old BL', 'AU', 'AC']
TAGS_USAR = final.drop(columns=[col for col in columnas_a_eliminar if col in final.columns], errors='ignore')

# --------------------------
# 2. Conversiones de tipos y limpieza de formato
# --------------------------

# a) Num Tarjeta: convertir a objeto (string)
if 'Num Tarjeta' in TAGS_USAR.columns:
    TAGS_USAR['Num Tarjeta'] = TAGS_USAR['Num Tarjeta'].astype(str)

# b) Fecha Transacción: intentar convertir a datetime
if 'Fecha Transacción' in TAGS_USAR.columns:
    TAGS_USAR['Fecha Transacción'] = pd.to_datetime(TAGS_USAR['Fecha Transacción'], errors='coerce')

# c) Hora Transacción: convertir a formato hora (si la columna solo contiene horas, se pueden combinar en un datetime o extraer la hora)
if 'Hora Transacción' in TAGS_USAR.columns:
    # Suponiendo que el formato es HH:MM:SS u otro similar, se convierte a datetime y se extrae la hora
    TAGS_USAR['Hora Transacción'] = pd.to_datetime(TAGS_USAR['Hora Transacción'], format='%H:%M:%S', errors='coerce').dt.time

# d) IEPS: convertir a float64 (se asume que puede venir con formato no numérico)
if 'IEPS' in TAGS_USAR.columns:
    TAGS_USAR['IEPS'] = TAGS_USAR['IEPS'].apply(limpiar_a_float)

# e) Importe Transacción: convertir a float64, limpiando formato ($ y comas)
if 'Importe Transacción' in TAGS_USAR.columns:
    TAGS_USAR['Importe Transacción'] = TAGS_USAR['Importe Transacción'].apply(limpiar_a_float)

# f) Comision: convertir a float64, limpiando formato si es necesario
if 'Comision' in TAGS_USAR.columns:
    TAGS_USAR['Comision'] = TAGS_USAR['Comision'].apply(limpiar_a_float)

# g) Subtotal: convertir a float64, limpiando formato
if 'Subtotal' in TAGS_USAR.columns:
    TAGS_USAR['Subtotal'] = TAGS_USAR['Subtotal'].apply(limpiar_a_float)

# h) Cantidad Mercancía: convertir a float64
if 'Cantidad Mercancía' in TAGS_USAR.columns:
    TAGS_USAR['Cantidad Mercancía'] = TAGS_USAR['Cantidad Mercancía'].apply(limpiar_a_float)

# i) KG C02: convertir a float64
if 'KG C02' in TAGS_USAR.columns:
    TAGS_USAR['KG C02'] = TAGS_USAR['KG C02'].apply(limpiar_a_float)

# j) Precio Unitario: convertir a float64
if 'Precio Unitario' in TAGS_USAR.columns:
    TAGS_USAR['Precio Unitario'] = TAGS_USAR['Precio Unitario'].apply(limpiar_a_float)

# k) Rendimiento: convertir a float64
if 'Rendimiento' in TAGS_USAR.columns:
    TAGS_USAR['Rendimiento'] = TAGS_USAR['Rendimiento'].apply(limpiar_a_float)

# l) Id Conductor: quitar $ y comas, mantener como objeto
if 'Id Conductor' in TAGS_USAR.columns:
    TAGS_USAR['Id Conductor'] = TAGS_USAR['Id Conductor'].apply(limpiar_id_conductor)

# m) Importe Neto: convertir a float64, limpiando formato ($ y comas)
if 'Importe Neto' in TAGS_USAR.columns:
    TAGS_USAR['Importe Neto'] = TAGS_USAR['Importe Neto'].apply(limpiar_a_float)

# n) IVA: convertir a float64, limpiando formato ($ y comas)
if 'IVA' in TAGS_USAR.columns:
    TAGS_USAR['IVA'] = TAGS_USAR['IVA'].apply(limpiar_a_float)

<ipython-input-27-ad0e37805603>:25: DtypeWarning: Columns (5,21,22,37,39,41,44,45,52,53,54,55,56,57,58,59,60,61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  final = pd.read_csv(ruta_original)

In [ ]:
# Recorremos cada columna del dataframe
for col in TAGS_USAR.columns:
    # Eliminamos los valores nulos para evitar confusiones con NaN
    non_null_values = TAGS_USAR[col].dropna()

    # Obtenemos el conjunto de tipos de dato presentes en la columna
    unique_types = non_null_values.apply(lambda x: type(x)).unique()

    # Si hay más de un tipo de dato, se considera que hay mezcla/inconsistencia
    if len(unique_types) > 1:
        print(f"La columna '{col}' tiene tipos de datos mixtos: {unique_types}")

La columna 'PO' tiene tipos de datos mixtos: [<class 'str'> <class 'int'>]
La columna 'No Comprobante' tiene tipos de datos mixtos: [<class 'str'> <class 'int'>]
La columna 'Id Mercancía' tiene tipos de datos mixtos: [<class 'str'> <class 'int'>]
La columna 'Id Conductor' tiene tipos de datos mixtos: [<class 'str'> <class 'float'>]
La columna 'No Estación Pemex' tiene tipos de datos mixtos: [<class 'str'> <class 'int'>]
La columna 'Número de Control' tiene tipos de datos mixtos: [<class 'str'> <class 'int'>]
La columna 'Folio' tiene tipos de datos mixtos: [<class 'str'> <class 'int'>]

In [ ]:
# Lista de columnas que tienen tipos de datos mixtos
cols_mixtas = [
    'PO',
    'No Comprobante',
    'Id Mercancía',
    'No Estación Pemex',
    'Número de Control',
    'Folio',
    'Id Conductor'
]

# Convertimos cada columna a string
for col in cols_mixtas:
    TAGS_USAR[col] = TAGS_USAR[col].astype(str)

In [ ]:
import pandas as pd
import numpy as np

# Función para redondear tiempos a intervalos de 15 minutos
def redondear_hora(tiempo_str):
    """
    Recibe un string en formato 'HH:MM:SS' y devuelve un string en formato 'HH:MM'
    redondeado al intervalo de 15 minutos más cercano:
        - El redondeo se hace de forma estándar:
          por ejemplo, si los minutos están entre 0 y 7 se redondea a HH:00;
          entre 8 y 22 a HH:15; entre 23 y 37 a HH:30; entre 38 y 52 a HH:45;
          y si es 53 o más se redondea a la siguiente hora (HH+1:00).
    """
    try:
        # Convertir el string a un objeto datetime
        dt = pd.to_datetime(tiempo_str, format='%H:%M:%S', errors='coerce')
        if pd.isna(dt):
            return np.nan
        hora = dt.hour
        minuto = dt.minute

        # Redondear los minutos al múltiplo de 15 más cercano
        # Usamos round para el redondeo; si el resultado es 60, se ajusta a la siguiente hora.
        nuevo_minuto = int(round(minuto / 15) * 15)
        if nuevo_minuto == 60:
            nuevo_minuto = 0
            hora = (hora + 1) % 24  # Ajuste en caso de que pase la medianoche

        return f"{hora:02}:{nuevo_minuto:02}"
    except Exception as e:
        # En caso de error, retorna el valor original
        return tiempo_str

# Procesar la columna "Hora Transacción": redondear la hora a intervalos de 15 minutos
if 'Hora Transacción' in TAGS_USAR.columns:
    TAGS_USAR['Hora Transacción'] = TAGS_USAR['Hora Transacción'].apply(redondear_hora)

In [ ]:
df = TAGS_USAR

In [ ]:
description = pd.DataFrame({
    'Nombre': df.columns,
    'Tipo de Dato': df.dtypes.values,
    'Valores Únicos': [df[col].nunique() for col in df.columns],
    'Valores Nulos': df.isnull().sum().values
})
print("\nDescripción de las variables:")
print(description)

Descripción de las variables:
                    Nombre    Tipo de Dato  Valores Únicos  Valores Nulos
0                    Month          object              12              0
1          Id Grupo Región          object               8              5
2         Grupo de Región           object               2          13542
3                  Cliente          object              16              0
4                  Factura          object             229              0
5                       PO          object             208              0
6                       GR          object             154          16594
7                Id Región          object              33              5
8                    Serie          object             663              0
9             No Economico          object             383          13550
10                Division          object               6              0
11                      BL          object              20              0
12                  SUB BL          object              29          13542
13                      CC          object              33          13542
14  Identificador Vehículo          object             592              0
15                Vehículo          object             945              0
16                   Placa          object             672              0
17             Num Tarjeta          object             648              0
18               Num Serie          object            1189              0
19       Fecha Transacción  datetime64[ns]             599          29352
20        Hora Transacción          object              91            414
21          No Comprobante          object           47627              0
22            Id Mercancía          object               3              0
23               Mercancía          object              11              0
24      Km Ant Transacción         float64           40947            516
25          Km Transacción         float64           41352              3
26               Recorrido         float64            4787            518
27                   IVA %         float64               1              0
28                    IEPS         float64            8384              0
29     Importe Transacción         float64           33684              0
30                Comision         float64            4549              0
31                Subtotal         float64           35258              0
32      Cantidad Mercancía         float64           12285              0
33                  KG C02         float64           16655            308
34                 TON C02         float64             215             82
35                 Arboles         float64            4477             82
36         Precio Unitario         float64            1199              0
37             Rendimiento         float64              80              0
38        Rendimiento Real         float64            6199              0
39            Id Conductor          object            2227              0
40               Conductor          object            1007             35
41       No Estación Pemex          object             862              0
42   Razón Social Afiliado          object             767              0
43                     RFC          object             553              0
44       Número de Control          object             383              0
45                   Folio          object             289              0
46             Observación          object              24           4439
47               Respuesta          object               6            145
48                     Año           int64               4              0
49            Importe Neto         float64           29063           8936
50                     IVA         float64           14295          22274
51                  Estado          object               5           8936
52                   BL 2           object              20          35965
53              VIN Number          object             346          35965
54                Locacion          object               8          35227
55           No. Economico          object             509          35227
56                  Sub BL          object              42          35227

In [ ]:
# --------------------------
# 3. Guardar el DataFrame transformado en un nuevo CSV
# --------------------------
ruta_nuevo_csv = '/content/gdrive/MyDrive/Datos_TAGS/Datasets/Final/TAGS_USAR.csv'
TAGS_USAR.to_csv(ruta_nuevo_csv, index=False)  # index=False evita que se guarde la columna de índices

print(f"Columnas eliminadas y nuevo archivo guardado en: {ruta_nuevo_csv}")

Columnas eliminadas y nuevo archivo guardado en: /content/gdrive/MyDrive/Datos_TAGS/Datasets/Final/TAGS_USAR.csv